# Generated by Django 2.1.7 on 2019-03-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
