# Generated by Django 2.1.7 on 2019-03-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190323_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='./media/default.jpg', upload_to='venues'),
        ),
    ]
