# Generated by Django 2.1.7 on 2019-03-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_venue_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="venues"),
        ),
    ]
