# Generated by Django 2.1.7 on 2019-04-05 19:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_venue_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(default=2, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
