# Generated by Django 2.1.7 on 2019-04-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190405_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='cast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='copy',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(default='film', editable=False),
        ),
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
