# Generated by Django 2.1.7 on 2019-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_film_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='copy',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
