# Generated by Django 2.1.7 on 2019-05-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_venue_copy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='article',
            name='show_author',
            field=models.BooleanField(blank=True, default='True', help_text='Deselect if you want to hide the author'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_date',
            field=models.BooleanField(blank=True, default='True', help_text='Deselect if you want to hide the date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Dimensions 1200px+ width work best', upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Dimensions 1200px+ width work best', upload_to='films'),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.PositiveIntegerField(help_text='In minutes', null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, help_text='Youtube or Vimeo link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='copy',
            field=models.TextField(blank=True, help_text='Only if the screening needs special copy', max_length=2000),
        ),
        migrations.AlterField(
            model_name='screening',
            name='name',
            field=models.CharField(blank=True, help_text='Only if the screening needs a special title', max_length=100),
        ),
        migrations.AlterField(
            model_name='screening',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Only if the screening needs a special subtitle', max_length=100),
        ),
        migrations.AlterField(
            model_name='screening',
            name='tickets',
            field=models.URLField(blank=True, help_text='Link to external tickets page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Dimensions 1200px+ width work best', upload_to='seasons'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook',
            field=models.CharField(blank=True, help_text='Username only', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Dimensions 1200px+ width work best', upload_to='venues'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='twitter',
            field=models.CharField(blank=True, help_text='Username only, no @', max_length=25),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, help_text='Full URL including https://', max_length=50, null=True),
        ),
    ]
