# Generated by Django 2.2.1 on 2019-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190512_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='copy',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='quote',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='programme',
            name='copy',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='copy',
            field=models.TextField(blank=True, help_text='Only if the screening needs special copy', max_length=1000),
        ),
        migrations.AlterField(
            model_name='season',
            name='copy',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='copy',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
