# Generated by Django 2.2.1 on 2019-05-26 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_article_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Film'),
        ),
    ]
