# Generated by Django 2.2.1 on 2019-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190810_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
