from django.urls import path
from .views import (
    HomeView,
    VenueListView,
    VenueDetailView,
    VenueCreateView,
    VenueUpdateView,
    VenueDeleteView,
    FilmListView,
    FilmDetailView,
    FilmCreateView,
    FilmUpdateView,
    FilmDeleteView,
    SeasonListView,
    SeasonDetailView,
    SeasonCreateView,
    SeasonUpdateView,
    SeasonDeleteView,
    ScreeningListView,
    ScreeningDetailView,
    ScreeningCreateView,
    ScreeningUpdateView,
    ScreeningDeleteView,
)
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('venues/', VenueListView.as_view(), name='venues'),
    path('venue/<str:slug>-<int:pk>/',
         VenueDetailView.as_view(), name='venue-detail'),
    path('venue/new/',
         VenueCreateView.as_view(), name='venue-create'),
    path('venue/<str:slug>-<int:pk>/update/',
         VenueUpdateView.as_view(), name='venue-update'),
    path('venue/<str:slug>-<int:pk>/delete/',
         VenueDeleteView.as_view(), name='venue-delete'),

    path('films/', FilmListView.as_view(), name='films'),
    path('film/<str:slug>-<int:pk>/',
         FilmDetailView.as_view(), name='film-detail'),
    path('film/new/',
         FilmCreateView.as_view(), name='film-create'),
    path('film/<str:slug>-<int:pk>/update/',
         FilmUpdateView.as_view(), name='film-update'),
    path('film/<str:slug>-<int:pk>/delete/',
         FilmDeleteView.as_view(), name='film-delete'),

    path('seasons/', SeasonListView.as_view(), name='seasons'),
    path('season/<str:slug>-<int:pk>/',
         SeasonDetailView.as_view(), name='season-detail'),
    path('season/new/',
         SeasonCreateView.as_view(), name='season-create'),
    path('season/<str:slug>-<int:pk>/update/',
         SeasonUpdateView.as_view(), name='season-update'),
    path('season/<str:slug>-<int:pk>/delete/',
         SeasonDeleteView.as_view(), name='season-delete'),

    path('screenings/', ScreeningListView.as_view(), name='screenings'),
    path('screening/<str:slug>-<int:pk>/',
         ScreeningDetailView.as_view(), name='screening-detail'),
    path('screening/new/',
         ScreeningCreateView.as_view(), name='screening-create'),
    path('screening/<str:slug>-<int:pk>/update/',
         ScreeningUpdateView.as_view(), name='screening-update'),
    path('screening/<str:slug>-<int:pk>/delete/',
         ScreeningDeleteView.as_view(), name='screening-delete'),
]
